### ISSUE TITLE
docker exec -w /etc/caddy caddy caddy reload doesn't work

### ISSUE THREAD

**Issue by albotroz** [StarWhiz/docker_deployment_notes#6]
After I edit Caddyfile and use:
`docker exec -w /etc/caddy caddy caddy reload`

result is:
```
{"level":"info","ts":1708475357.2048461,"msg":"using adjacent Caddyfile"}
{"level":"warn","ts":1708475357.205982,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"Caddyfile","line":2}
```

My Caddyfile:

```
portainer.{$MY_DOMAIN} {
  reverse_proxy portainer:9443 {
    transport http {
      tls
      tls_insecure_skip_verify
    }
  }
}

mumble.{$MY_DOMAIN} {
        reverse_proxy mumble-server:64738
}
```

**Comment by StarWhiz** [comment]
Sorry just saw your comment.

If you notice what the error message mentioned... it said line 2 is in the incorrect format. You should use consistent spacing with tabs like so... Try to manually tab the spacing. Copy paste from browser might not be perfect

```
portainer.{$MY_DOMAIN} {
        reverse_proxy portainer:9443 {
                transport http {
                        tls
                        tls_insecure_skip_verify
                }
        }
}

mumble.{$MY_DOMAIN} {
        reverse_proxy mumble-server:64738
}
```

Alternatively, `docker-compose down` on your caddy instance
modify your /caddy/docker-compose.yml

so that 
```
   volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
```
becomes

```
   volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
```

then `docker-compose up -d` then run the following command to fix the format as mentioned in the error message

`docker exec -w /etc/caddy caddy caddy fmt --overwrite`

That command will auto fix the formatting for you.

Then you can proceed with `docker exec -w /etc/caddy caddy caddy reload` without issue
